### PR TITLE
Fixed the plugin to start the server before the tests and the tested app are imported.

### PR DESCRIPTION
**Pull request by warvariuc**

### CODE REVIEW

**Comment by theorm** [comment]
@warvariuc thanks for the fix. Could you please update configuration details in `README.md` as well?

**Comment by warvariuc** [comment]
You mean to add nose2 usage details?

**Comment by theorm** [comment]
Exactly. I did it with your previous pull request, but now I see that something is changed in the comment section of `nose2_plugin.py`. It could be just spaces. But if text is changed, just update it in the `README.md` and I'll merge it. Thanks!

**Comment by warvariuc** [comment]
But there is no any info in `README` concerning nose2 at all right now.

**Comment by theorm** [comment]
Sorry, my bad. I pushed the new version tag but no master. The update is in master now.

**Comment by warvariuc** [comment]
Done.

**Pull request merged**
